name: CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
#    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build Release App
        run: ./gradlew :desktop:packageDistributionForCurrentOS

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributable-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            desktop/build/**/*.exe
            desktop/build/**/*.dmg

      - name: Release
        uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
        with:
          files: |
            desktop/build/**/*.exe
            desktop/build/**/*.dmg


#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}